services:
  php82:
    build:
      context: ./apps/ide
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - jb-network

networks:
  jb-network:
    driver: bridge